### ISSUE TITLE
Arduino:79: error: 'class KeyboardController' has no member named 'attachReportReader'

### ISSUE THREAD

**Issue by mattherdelma** [earthlion/SerialProxy#1]
I installed the required software carefully according to the tutorial and set it up correctly, but when I verified the Arduino.ino file in the Arduino software, the problem of **'class KeyboardController' has no member named'attachReportReader'** appeared. I have searched Google for a day and I haven't found a solution. How can I solve this?thanks

**Comment by earthlion** [comment]
https://github.com/earthlion/SerialProxy/blob/main/Arduino/USBHost_t36.h
